Start timer
matatoMatata94/roundONE pull request #1
Opened 2021-01-25 22:27 UTC by matatoMatata94

2021-01-27 11:59 UTC, MuTe33 commented on lib/common_widgets/custom_row_widget.dart
> +              size: iconSize == null ? 90 : iconSize,
Mach daraus einen default parameter im Widget constructor falls du die eine Größe nur für ein Widget anpasst

2021-01-27 12:00 UTC, MuTe33 commented on lib/common_widgets/custom_row_widget.dart
>                color: iconColor == null ? Colors.red : iconColor,
selbe hier. Default farbe wenn die sowieso immer gleich bleibt

2021-01-27 12:00 UTC, MuTe33 commented on lib/common_widgets/start_button.dart
> +          Navigator.push(context, ConcentricPageRoute(builder: (ctx) {
Warum `ConcentricPageRoute`?

2021-01-27 20:45 UTC, matatoMatata94 commented on lib/common_widgets/start_button.dart
> +          Navigator.push(context, ConcentricPageRoute(builder: (ctx) {
War Copy-Paste von Stackoverflow. Wollte eine schöne Animation für den Übergang aber der Button sieht dann komisch aus. Arbeite noch an einer anderen Lösung.

2021-01-27 20:45 UTC, matatoMatata94 commented on lib/common_widgets/start_button.dart
> +          Navigator.push(context, ConcentricPageRoute(builder: (ctx) {
Irgendwelche Ideen? :D

2021-02-02 19:32 UTC, MuTe33 requested changes
ein paar sachen

2021-02-02 19:32 UTC, MuTe33 commented on lib/common_widgets/cupertino_time_picker_button.dart
> +                return shownDuration;
wie greifst du auf `shownDuration` zu?

2021-02-02 19:32 UTC, MuTe33 commented on lib/common_widgets/number_picker_button.dart
> +  int get shownNumber => null;
Das ist ein getter, der dir immer null zurück geben, nie einen anderen Wert. Den getter kannst du auch anders schreiben wie:

```dart
int getShownNumber(){
   return null;
}
```

2021-02-02 19:32 UTC, MuTe33 commented on lib/common_widgets/number_picker_button.dart
> +    print(shownNumber);
du printest eine Funktion bzw. gibst eine funktion zurück. Umwirkloch darauf zugreifen zu können musst du `widget.shownNumber` machen  da du im Stateful WIdget bist. Außerdem willst du glaube oben keine Funktion sondern eher eine Variable kann. das sein?

2021-02-02 19:32 UTC, MuTe33 commented on lib/common_widgets/start_button.dart
> +          color: Colors.red,
default parameter ist doch schon red.

2021-02-09 20:27 UTC, merged